# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

# we require defaults
if ! ENV.has_key?("EMAIL_SETUP")
  puts 'required environment variables not setup, please source defaults'
  exit 1
end

# setup environment variables
env_config = {}
ENV.each do |k, v|
  if k.match(/^EMAIL/)
    env_config[k] = v
  end
end

# setup volumes to share
volumes_to_share = Array.new
env_config['EMAIL_SHARED_VOLUMES'].strip.split(' ').each do |entry|
 volumes_to_share.push('--volumes-from')
 volumes_to_share.push(entry)
end
# setup directories to share
directories_to_share = env_config['EMAIL_SHARED_DIRECTORIES'].strip.split(' ')

Vagrant.configure("2") do |config|
  config.vm.define "email" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "email"
      d.link("mysql:mysql")
      d.env = env_config
      d.create_args = volumes_to_share
#      d.volumes = directories_to_share
    end
  end
end
