# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

Vagrant.configure("2") do |config|
  config.vm.define "centos" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "centos"
      d.create_args = ["-h", "centos"]
      d.has_ssh = true
    end
  end
end
