# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

# we require defaults
if ! ENV.has_key?("PLEX_SETUP")
  puts 'required environment variables not setup, please source defaults'
  exit 1
end

# setup environment variables
env_config = {}
ENV.each do |k, v|
  if k.match(/^PLEX/)
    env_config[k] = v
  end
end

# setup directories to share
directories_to_share = env_config['PLEX_SHARED_DIRECTORIES'].strip.split(' ')

Vagrant.configure("2") do |config|
  config.vm.define "plex" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "plex"
      d.env = env_config
      d.create_args = ['--net="host"']

      # add your own mapping here
      d.volumes = directories_to_share
    end
  end
end
