# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

Vagrant.configure("2") do |config|
  config.vm.define "wordpress" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "wordpress"
      d.remains_running = false
      d.volumes = ["/var/www/blog"]
    end
  end
end
