# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

# we require defaults
if ! ENV.has_key?("PHPFPM_SETUP")
  puts 'required environment variables not setup, please source defaults'
  exit 1
end

# setup environment variables
env_config = {}
ENV.each do |k, v|
  if k.match(/^PHPFPM/)
    env_config[k] = v
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "phpfpm" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "phpfpm"
      d.link("memcached:memcached")
      d.link("mysql:mysql")
      d.env = env_config
      d.create_args = ["--volumes-from", "owncloud", "--volumes-from", "wordpress"]
    end
  end
end
